---
- name: Clone a repo with separate git directory
  git:
    repo: "{{repo}}"
    dest: "{{dest}}"
    clone: yes
    version: front
    update: yes
    force: true

- name: Install packages
  npm:
   name: "install"
   path: "{{path_npm}}"

- name: build
  npm:
   name: "build"
   path: "{{path_build}}"
